#!/bin/bash

set -e

TODAY=$(date --iso-8601)

# external modules
make M=../soft_3rdpart/wave511/code/vdi/linux/driver LOCALVERSION=-r0b0-$TODAY -j $(nproc)
ls ../soft_3rdpart/wave511/code/vdi/linux/driver/vdec.ko
make M=../soft_3rdpart/codaj12/jdi/linux/driver LOCALVERSION=-r0b0-$TODAY -j $(nproc)
ls ../soft_3rdpart/codaj12/jdi/linux/driver/jpu.ko
make M=../soft_3rdpart/wave420l/code/vdi/linux/driver LOCALVERSION=-r0b0-$TODAY -j $(nproc)
ls ../soft_3rdpart/wave420l/code/vdi/linux/driver/venc.ko

# echo make bindeb-pkg LOCALVERSION=-r0b0-$TODAY -j $(nproc)
make bindeb-pkg LOCALVERSION=-r0b0-$TODAY -j $(nproc)

echo cd ..
echo ./publish_deb.sh *.deb
echo cd visionfive2-linux-deb-repo

