#!/bin/bash

set -e

# TODAY=$(date --iso-8601)
# MAKEOPTS="LOCALVERSION=-r0b0-$TODAY -j $(nproc)"
MAKEOPTS="LOCALVERSION=-r0b0 -j $(nproc)"

make olddefconfig $MAKEOPTS
make vmlinux $MAKEOPTS
make modules $MAKEOPTS

# external modules
make M=../soft_3rdpart/wave511/code/vdi/linux/driver $MAKEOPTS
make M=../soft_3rdpart/codaj12/jdi/linux/driver $MAKEOPTS
make M=../soft_3rdpart/wave420l/code/vdi/linux/driver $MAKEOPTS

make bindeb-pkg $MAKEOPTS

echo cd ..
echo ./publish_deb.sh *.deb
echo cd visionfive2-linux-deb-repo

