name: bindeb-pkg
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:trixie
    steps:
      - uses: actions/checkout@v6
        with:
          path: src

      - name: Install packages and build
        run: |
          export TODAY=$(date --iso-8601)
          dpkg --add-architecture riscv64
          apt -y update
          apt -y install libncurses-dev libssl-dev bc flex bison make build-essential crossbuild-essential-riscv64 debhelper-compat cpio kmod libelf-dev rsync libssl-dev:riscv64
          cd src
          cp config-r0b0 .config
          make O=$__kobj ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- olddefconfig
          make O=$__kobj ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- bindeb-pkg LOCALVERSION=-r0b0-$TODAY -j$(nproc)

      - uses: actions/upload-artifact@v7
        with:
          name: "Debian packages"
          compression-level: 0
          path: "*.deb"
